# 示例配置文件
# 将此文件另存为 example_config.yaml 并根据需要修改

experiment_name: "my_ner_experiment"
description: "使用BERT在生物医学数据上训练NER模型"
tags: ["ner", "biomedical", "bert"]

model:
  model_name: "bert-base-cased"
  cache_dir: "./cache"
  trust_remote_code: false
  
  # 模型架构参数
  num_labels: null  # 自动从数据集推断
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1

data:
  # 数据集配置
  dataset_name: "bc2gm_corpus"
  dataset_config: "bc2gm_corpus"
  
  # 或者使用本地文件
  # train_file: "./data/train.json"
  # validation_file: "./data/dev.json"
  # test_file: "./data/test.json"
  
  # 数据预处理参数
  max_length: 512
  padding: "max_length"
  truncation: true
  label_all_tokens: false
  
  # 列名配置
  text_column_name: "tokens"
  label_column_name: "ner_tags"

training:
  # 输出配置
  output_dir: "./results"
  
  # 基础训练参数
  num_train_epochs: 3
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  learning_rate: 5e-5
  weight_decay: 0.01
  adam_epsilon: 1e-8
  max_grad_norm: 1.0
  
  # 学习率调度
  lr_scheduler_type: "linear"
  warmup_ratio: 0.1
  warmup_steps: 0
  
  # 评估和保存策略
  evaluation_strategy: "epoch"
  eval_steps: null
  save_strategy: "epoch"
  save_steps: null
  save_total_limit: 2
  load_best_model_at_end: true
  metric_for_best_model: "eval_f1"
  greater_is_better: true
  
  # 早停
  early_stopping_patience: 3
  early_stopping_threshold: 0.0
  
  # 混合精度训练 (推荐启用以加速训练)
  fp16: true
  fp16_opt_level: "O1"
  bf16: false
  
  # 优化参数
  gradient_accumulation_steps: 1
  dataloader_num_workers: 0
  
  # 日志配置
  logging_steps: 100
  report_to: []  # 不使用外部报告工具
  
  # 随机种子
  seed: 42
  
  # Hub配置 (如果要推送到Hugging Face Hub)
  push_to_hub: false
  # hub_model_id: "your-username/your-model-name"
  # hub_token: "your-hub-token"

evaluation:
  # 评估指标
  metrics: ["seqeval"]
  compute_metrics_each_eval: true
  
  # 预测配置
  do_predict: true
  
  # 输出配置
  output_predictions: true
  predictions_file: "predictions.txt"
  output_results: true
  results_file: "results.json"

# 环境配置
cuda_visible_devices: null  # 使用所有可用GPU
local_rank: -1

# 使用方法:
# python run_training.py --config example_config.yaml
